# Copy this file to .streamlit/secrets.toml and add your actual API keys

[default]
PERPLEXITY_API_KEY = "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"

# To get a Perplexity API key:
# 1. Sign up at https://www.perplexity.ai/
# 2. Navigate to API settings
# 3. Generate a new API key
# 4. Replace "your_perplexity_api_key_here" with your actual key